### ISSUE TITLE
Agregar teammates

### ISSUE THREAD

**Issue by Rammsoad-Sixx** [Rammsoad-Sixx/github-lessons#2]
Agregar a teammates

- [x] Daniel Escamilla
- [x] Jaime Contreras
- [x] Enrique Amaya
- [x] Gina Fraire 
- [x] Giordy Romero

**Comment by Rammsoad-Sixx** [comment]
cerrar porque ya lo hice

**Comment by kyskyky** [comment]
Hola equipo de trabajo.

**Comment by Rammsoad** [comment]
tambien yo puedo comentar
